spring.application.name=Moventia
spring.datasource.url=jdbc:postgresql://localhost:5432/Moventia
spring.datasource.username=Your_postgres_username
spring.datasource.password=Your_postgres_password

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=YourSecret32characterkey
jwt.expiration-ms=anytime
