spring.application.name=Moventia
spring.datasource.url=jdbc:postgresql://localhost:5432/Moventia
spring.datasource.username=postgres
spring.datasource.password=Jash1234

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=ThisIsAVeryLongSecretKeyForMoventiaAppThatIsAtLeast32Chars
jwt.expiration-ms=86400000

# File Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

tmdb.api.key=ea5163767eecc5913224bb04c4315e1f
tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.image.base-url=https://image.tmdb.org/t/p/w500